### ISSUE TITLE
some knives don't work

### ISSUE THREAD

**Issue by xxlilx** [singhhdev/cs2-internal-skin-changer#8]
which is to say:
- Falchion
- Bowie
- Shadow Daggers

**Comment by Mespeet** [comment]
How did you build it? I cannot build in vs2022. Seems as if you have to use vs2010 but idk

**Comment by singhhdev** [comment]
ill fix this issue

**Comment by Mespeet** [comment]
> > How did you build it? I cannot build in vs2022. Seems as if you have to use vs2010 but idk
> 
> i use vs22, XD

So how'd you fix the freetype error?
